### ISSUE TITLE
structured light

### ISSUE THREAD

**Issue by nesquik011** [Arvind-Kumar-Thumati/3D-scanner-prototype#1]
hellow is it structured light ?

**Comment by Arvind-Kumar-Thumati** [comment]
Nah, it's based on Lidar distance sensing, structured light is a lot
expensive than Lidar but it is much more efficient.

**Comment by nesquik011** [comment]
what do i need to build ? list of requirements ?got video ?

**Comment by Arvind-Kumar-Thumati** [comment]
There are already a lot of projects like these , currently I have a problem
with ny arduino so just surf the net about 3d scanning with arduino and
lidar and you may find the required... If you aren't able to find it let
me know.
